### ISSUE TITLE
App wont start without Internet connection

### ISSUE THREAD

**Issue by theRealBitcoinClub** [paytaca/paytaca-app#72]
**I made a test blocking the app in my firewall setting**

**Then I started the app and it shows a blank screen**

I would expect the app to either:

1. Show a warning to the user that Internet is missing
2. Let the user use it in offline mode to receive payments via QR code or to copy his address for share

_Its a common use case that the receiver of a payment might not have connection but as long as the sender does everything is fine and payment can still be received_

![Screenshot_20221028-055311_NetGuard](https://user-images.githubusercontent.com/35400618/198560960-94b987e9-c613-4446-bdda-ea43b01be45f.jpg)

![Screenshot_20221028-055255_Paytaca](https://user-images.githubusercontent.com/35400618/198561005-e2931cab-d66c-41b7-a9aa-6505873ea537.jpg)

**Comment by joemarct** [comment]
Thanks for reporting this. It's already designed to load even if there is no internet connection so that, as you mentioned, the recipient can still show his/her receiving address and get paid. We didn't know this is just showing blank in other devices or maybe Android versions. Can you provide here the phone brand and model? And better if you can also provide the Android version. Thank you!

**Comment by theRealBitcoinClub** [comment]
The difference here is that I specifically block the traffic with a firewall

You might be using some APIs that supposedly give you information about active connection but they dont really do a test ping

**Comment by joemarct** [comment]
> The difference here is that I specifically block the traffic with a firewall

@theRealBitcoinClub If you get the chance, can you check if the app now loads even if blocked with a firewall?

**Comment by joemarct** [comment]
We have tested this on our end and the issue has been resolved.
